- name: install packages
  hosts: local
  connection: local
  vars:
    topics: linux, shell, ansible
    tagsmap:
      name: ansible
      project: roboshop
      component: catalogue
    taglist: [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
    ]

  tasks:
  - name: greeting
    ansible.builtin.debug:
      msg: "Hi Pavan, {{ GREETING | default('Good Morning') }}"

  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "{{ tagsmap | dict2items }}"
  
  - name: convert list to map
    ansible.builtin.debug:
      msg: "{{ taglist | items2dict }}"